spring.application.name=Stackoverflow
spring.datasource.hikari.auto-commit=false

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d92j54cm0tmc73e7ok80-a:5432/blog_webapp_jbid
spring.datasource.username=blog_webapp_jbid_user
spring.datasource.password=IULPpbMU3pTkBmEOudSApmU1P2hDq9Sr

# Cloudinary
cloudinary.cloud_name=dqmjfe5mg
cloudinary.api_key=557489714383712
cloudinary.api_secret=UB5wcoL5l9abCGVviH8Wr3FgxDc

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# File upload settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
